# Generated by Django 4.1.4 on 2023-07-19 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Authors',
        ),
    ]
